import type { Metadata } from "next";
import "./globals.css";
import NextAuthProvider from "@/provider/NextAuthProvider";
import { ThemeProvider } from "@/provider/theme-provider";
import TanStackQueryProvider from "@/provider/TanstackProvider";
import { LanguageProvider } from "@/contexts/LanguageContext";
import { Inter } from "next/font/google";

// If loading a variable font, you don't need to specify the font weight
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ApresentAI",
  description: "Generated by Inventu",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <TanStackQueryProvider>
      <NextAuthProvider>
        <LanguageProvider>
          <html lang="en">
            <body className={`${inter.className} antialiased`}>
              <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
                {children}
              </ThemeProvider>
            </body>
          </html>
        </LanguageProvider>
      </NextAuthProvider>
    </TanStackQueryProvider>
  );
}
