import type { Metadata } from "next";
import "./globals.css";
import NextAuthProvider from "@/provider/NextAuthProvider";
import { ThemeProvider } from "@/provider/theme-provider";
import TanStackQueryProvider from "@/provider/TanstackProvider";
import { LanguageProvider } from "@/contexts/LanguageContext";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ApresentAI",
  description: "Generated by Inventu",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <NextAuthProvider>
          <LanguageProvider>
            <TanStackQueryProvider>
              <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
                {children}
              </ThemeProvider>
            </TanStackQueryProvider>
          </LanguageProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
